sanity-io/pkg-utils

- package.json
- playground/custom-dist/package.json
- playground/exports-dummy/package.json
- playground/multi-export/package.json
- playground/ts/package.json
- src/node/_core/pkg/_parseExports.ts
- src/node/_core/pkg/_types.ts
- src/node/_core/pkg/_validatePkg.ts
- test/_parseExports.test.ts
When adding `pkg.exports` it's important to add `./package.json` to the list, otherwise, we're blocking people from being able to [read metadata from it](https://github.com/sanity-io/incompatible-plugin#usage) when in a native node env:
```ts
const {version} = require('sanity/package.json')
```
or
```ts
import {version} from 'sanity/package.json' assert {type: 'json'}
```
or
```ts
const {version} = await import('sanity/package.json', {assert: {type: 'json'}})
```
[Here's a PR with a repro case.](https://github.com/sanity-io/next-sanity/pull/134)
> feat: add support for `./package.json` in `pkg.exports`

- playground/ts/src/index.ts
- playground/ts/src/module1.ts
- playground/ts/src/module2.ts
- playground/ts/src/not-imported.ts
- src/node/_tasks/dts/_declareModuleFix.ts
- src/node/_tasks/dts/_doExtract.ts
- test/__snapshots__/cli.test.ts.snap
- test/_extractModuleBlocks.test.ts
- test/cli.test.ts
Espen discovered that the previous "fix" included `declare module` statements from test files as well as from TSDocs.
The code is not getting better with this, and we definitely should consider another approach, but dont have an TypeScript AST integration on hand right now unfortunatly.
**Update**
Files are now determined via `extractor.program.getSourceFiles()`: this is a bit better than glob for files ourself, and they already contain `text` without comments (but with TSDccs), so saves on readtime.
Added an integration test for ts to check that commented blocks and unused code are not included.
> fix: filter out test modules and comments

- playground/custom-dist/package.json
- playground/exports-dummy/package.json
- playground/extra-bundles/package.json
- playground/js/package.json
- playground/multi-export/package.json
- playground/ts/package.json
- scripts/build.ts
- src/node/_core/pkg/_parseExports.ts
- src/node/_printExtractMessages.ts
- src/node/_resolveBuildContext.ts
- test/__snapshots__/cli.test.ts.snap
- test/_parseExports.test.ts
- test/_parseTasks.test.ts
- test/cli.test.ts
The fix to require exporting `./package.json` was a bit painful downstream, so this PR is to have this behavior behind the `--strict` flag.
> fix: require exported `package.json` behind `--strict` flag

- src/node/_tasks/dts/_declareModuleFix.ts
- test/_extractModuleBlocks.test.ts
Note: This is a temporary fix - I want to replace this approach with an AST-based approach instead.
When encountering multi-line comment blocks such as:
```
/**
* @beta
**/
```
The current code leaves the trailing ` **/`. The issue is that the logic sees that it is currently inside a comment and that the line includes the closing of the comment - which sets `insideComment` to false. This is correct for lines that _follow_ this one, but not _the current_ line. By adding a `continue`, we are telling it to now move on to the next line.
The real solution is to use an AST parser here, since there are plenty of pitfalls doing it the current way - lines that contain `*/` inside of a string but not a comment and similar, or that do not end with `*/` and has code directly following it etc.
> fix: syntax error on multi-line declared modules

- package.json
- playground/ts/src/module1.ts
- pnpm-lock.yaml
- src/node/_tasks/dts/_declareModuleFix.ts
- src/node/_tasks/dts/_doExtract.ts
- src/node/_tasks/dts/_extractModuleBlocks.ts
- src/node/_tasks/dts/_extractTypes.ts
- test/__snapshots__/cli.test.ts.snap
- test/_extractModuleBlocks.test.ts
This PR replaces the manual line-by-line approach of extracting declared modules with one that does so by parsing the file to an AST and extracting the found ts module definitions.
Also has the added bonus of including any TSDoc that might be in the declaration.
- There are some spacing changes. I am not 100% sure why, but don't see this as a big deal personally
- There was a test to see if `declare module` inside of comments were being included - this failed now because the extractor will keep those types of comments, and we don't strip them anymore. I think this is more in line with what you would expect.
- The source map url was not included previously - an unintended side effect as I see it. It doesn't point to a valid URL, but that is the case regardless of the extraction process.
> feat: use recast for extracting declared modules

- package.json
- pnpm-lock.yaml
- src/node/tasks/rollup/resolveRollupConfig.ts
Fixes this install warning:
```bash
npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
```
> fix: refactor to `@rollup/plugin-terser`

- src/node/tasks/rollup/resolveRollupConfig.ts
Related to https://github.com/terser/terser/issues/1320
Terser removes any unknown directives. `@sanity/preview-kit` and `next-sanity` needs this before they can start shipping minified code
> fix: support the `use client` directive

- playground/dummy-commonjs/package.config.ts
- playground/dummy-commonjs/package.json
- src/node/core/pkg/loadPkgWithReporting.ts
- src/node/core/pkg/types.ts
- src/node/core/pkg/validateExports.ts
- src/node/core/pkg/validatePkg.ts
- src/node/tasks/rollup/resolveRollupConfig.ts
In `@sanity/pkg-utils@2` we introduced a required `type` property in `package.json`. This causes issues in Next.js, where it does not interpret `type: "commonjs"` (which is the same as `type: undefined`) the same way as Node and Vite.
> fix: optional package type

- src/node/tasks/rollup/resolveRollupConfig.ts
Removing options that match defaults makes the codebase a little easier to maintain.
> chore: remove rollup defaults

- src/node/tasks/rollup/resolveRollupConfig.ts
As packages consumed by `pkg-utils` are typically consumed by other bundlers this optimization is a bit counter-intuitive.
For example look at: https://unpkg.com/browse/next-sanity@3.1.8/dist/studio/index.js
And line 17-18:
```js
import '@sanity/icons';
import '@sanity/ui';
```
This happens because the file that uses `@sanity/icons` and `@sanity/ui` is `NextStudioLoading`. And `NextStudioLoading` is used by `dist/studio/index.js` and [`dist/studio/loading.js`](https://unpkg.com/browse/next-sanity@3.1.8/dist/studio/loading.js).
[More info.](https://rollupjs.org/guide/en/#why-do-additional-imports-turn-up-in-my-entry-chunks-when-code-splitting)
> fix: disable transitive imports hoisting

- src/node/tasks/rollup/resolveRollupConfig.ts
Rollup v3 introduces a great new option called [`dynamicImportInCjs`](https://rollupjs.org/guide/en/#dynamic-import-in-commonjs-output).
Since we target Node 14 as our baseline we can safely use code like this:
```js
const pkg = await import('pkg')
```
And if `pkg` is ESM-only (no CJS exports) it'll work the same in both ESM and CJS in NodeJS environments.
However since we use `@babel/preset-env` this new option doesn't work as babel is transforming the dynamic `import()` calls to `require()`.
This PR fixes that by turning module transformation off in babel.
> fix: allow `dynamicImportInCjs` in rollup v3

- package.json
- playground/babel-plugin/package.config.ts
- playground/babel-plugin/package.json
- playground/babel-plugin/src/index.ts
- playground/babel-plugin/tsconfig.dist.json
- playground/babel-plugin/tsconfig.json
- playground/babel-plugin/tsconfig.settings.json
- pnpm-lock.yaml
- src/node/core/config/types.ts
- src/node/tasks/rollup/resolveRollupConfig.ts
The `@babel/preset-env` is already handling [`object-rest-spread`](https://github.com/babel/babel/blob/d5660665d028be9aa352bd7485cc1fd7a87ac02e/packages/babel-compat-data/data/plugins.json#L288-L299) and by the looks of it with our browserslist target we no longer need it.
This results in a pretty nice bundlesize decrease in generated JS 😌 
Before:
```js
function Component(_ref) {
let { foobar } = _ref,
props = _objectWithoutProperties(_ref, _excluded)
return jsx(FooBar, _objectSpread({ foobaz: true }, props))
}
const _excluded = ['foobar']
function _toPrimitive(input, hint) {
if (typeof input !== 'object' || input === null) return input
var prim = input[Symbol.toPrimitive]
if (prim !== undefined) {
var res = prim.call(input, hint || 'default')
if (typeof res !== 'object') return res …
```
> fix: remove @babel/plugin-proposal-object-rest-spread

- src/node/globFiles.ts
Fixes #84 and [related @sanity/plugin-kit issue](https://github.com/sanity-io/plugin-kit/issues/61).
> fix: globs not working on windows

- playground/default-export/package.json
- playground/multi-export/package.json
- playground/multi-exports-commonjs/package.json
- playground/ts-bundler/package.json
- playground/ts-node16/package.json
- playground/ts/package.json
- src/node/resolveBuildTasks.ts
Currently this is required for re-exports can be used:
```json
{
".": {
"source": "./src/index.js",
"require": "./dist/index.cjs",
"node": {
"import": "./dist/index.cjs.js",
"require": "./dist/index.cjs"
},
"import": "./dist/index.js",
"default": "./dist/index.js"
}
}
```
In this case, the "node.require" condition is **never used** because "require" comes first.
And so it can safely be removed, allowing us to simplify the package json's a little bit.
This PR enables `@sanity/pkg-utils` to build the CJS wrappers when this is done:
```json
{
".": {
"source": "./src/index.js",
"require": "./dist/index.cjs",
"node": {
"import": "./dist/index.cjs.js"
},
"import": "./dist/index.js",
"default": "./dist/index.js"
}
}
```
> fix: make "node.require" optional when re-exporting CJS

- package.json
- playground/babel-plugin/package.json
- playground/custom-dist/package.json
- playground/default-export/package.json
- playground/dummy-commonjs/package.json
- playground/dummy-module/package.json
- playground/multi-export/package.json
- playground/multi-exports-commonjs/package.json
- playground/ts-bundler/package.json
- playground/ts-node16/package.json
- playground/ts/package.json
- src/node/core/pkg/loadPkgWithReporting.ts
- src/node/core/pkg/types.ts
- src/node/core/pkg/validatePkg.ts
- test/parseExports.test.ts
When this pattern is used:
```json
{
".": {
"source": "./src/index.js",
"require": "./dist/index.cjs",
"node": {
"import": "./dist/index.cjs.js"
},
"import": "./dist/index.js",
"default": "./dist/index.js"
}
}
```
astro throws an error as it will use the `node.import` condition and isn't prepared to handle a re-export of CJS:
```bash
error   "default" is not exported by "../dummy-commonjs/dist/index.js", imported by "../dummy-commonjs/node/index.mjs".
File:
/Users/cody/Developer/GitHub/pkg-utils/playground/dummy-commonjs/node/index.mjs:1:7
Code:
1: import cjs from '../dist/index.js'
^
2: 
3: export const format = cjs.format
Stacktrace:
RollupError: "default" is not exported by "../dummy-commonjs/dist/index.js", imported by "../dummy-commonjs/node/index.mjs".
```
The solution is to add a …
> fix: improve astro compatibilty

- package.json
- playground/runtime-next-js/app/app-router/leaf.tsx
- playground/runtime-next-js/app/app-router/page.tsx
- playground/runtime-next-js/app/layout.tsx
- playground/runtime-next-js/next-env.d.ts
- playground/runtime-next-js/package.json
- playground/runtime-next-js/tsconfig.json
- playground/use-client-directive/package.config.ts
- playground/use-client-directive/package.json
- playground/use-client-directive/src/_exports.tsx
- playground/use-client-directive/src/index.ts
- playground/use-client-directive/tsconfig.dist.json
- playground/use-client-directive/tsconfig.json
- playground/use-client-directive/tsconfig.settings.json
- pnpm-lock.yaml
- src/node/core/config/types.ts
- src/node/tasks/rollup/resolveRollupConfig.ts
- src/node/tasks/rollup/rollupTask.ts
To enable out-of-the-box support for React Server Components.
> feat: add `use client` module directive support

- src/node/tasks/dts/doExtract.ts
Currently, if `doExtract` fails it throws an error including every message received during build, including warnings that are ignored by the current loglevel/package config. Combined with another issue that does't render error messages properly (not exactly sure where this happens, didn't dig into it), but rather console.logs the array of messages, the actual errors gets obscured by other messages (info, warnings, etc.) which in turn makes it hard to track down exactly what failed. This fixes this particular issue by making sure only _errors_ are attached to the thrown exception.
> fix: throw DtsError with errors only

- src/node/tasks/rollup/resolveRollupConfig.ts
I had some issues where npm run watch would only register changes once on WSL/NVIM, turns out there is something called safe-write that some editors implement. Either way it could be turned off in nvim with `:set backupcopy=yes`, or setting a usePolling property on the chokidar watch config, which is what rollup watch uses when available. How you want to implement this or if you want to is ofcourse up to you. Maybe detecting safe-write is possible. There is some discussion on this thread: https://github.com/parcel-bundler/parcel/issues/221#issuecomment-350883702
> feat: Chokidar use polling on rollup watch

- package.config.ts
- package.json
- playground/babel-plugin/package.json
- playground/custom-dist/package.json
- playground/dummy-commonjs/package.json
- playground/dummy-module/package.json
- playground/dummy-side-effects/package.json
- playground/multi-export/package.json
- playground/multi-exports-commonjs/package.json
- playground/ts-bundler/package.json
- playground/ts-node16/package.json
- playground/ts/package.json
- playground/use-client-directive/package.json
- src/node/check.ts
- src/node/core/pkg/loadPkgWithReporting.ts
- src/node/core/pkg/parseExports.ts
- src/node/printPackageTree.ts
- src/node/resolveBuildTasks.ts
- src/node/resolveWatchTasks.ts
- src/node/tasks/dts/doExtract.ts
- src/node/tasks/dts/dtsTask.ts
- src/node/tasks/dts/dtsWatchTask.ts
- src/node/tasks/dts/extractTypes.ts
- src/node/tasks/dts/getTargetPaths.ts
- src/node/tasks/dts/types.ts
- src/node/templates/default/template.ts
- test/cli.test.ts
- test/parseExports.test.ts
- test/parseTasks.test.ts
Fixes errors such as ["👺 Masquerading as ESM"](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/FalseESM.md) on:
- https://arethetypeswrong.github.io/?p=%40sanity%2Fpkg-utils%405.1
- https://publint.dev/@sanity/pkg-utils@5.1.0
> fix: ensure no "Masquerading as ESM|CJS" dts errors

- .github/workflows/browserslist.yml
- .github/workflows/format-if-needed.yml
- .github/workflows/release-please.yml
- playground/multi-exports-commonjs/package.json
- src/node/build.ts
- src/node/check.ts
- src/node/core/pkg/loadPkgWithReporting.ts
- src/node/watch.ts
More details in the original report https://github.com/sanity-io/ui/issues/1246 by @spencerbeggs.
This PR changes `@sanity/pkg-utils` so that it no longer requires specifying `type` when `legacyExports: true`. It's only when generating legacy exports that we deal with files that end in `.js` that are ESM and that are not declared in `pkg.exports`.
It also ensures that if `legacyExports: true` then we do not allow `type: commonjs` to ensure packages don't fall into this regression.
This PR is blocking https://github.com/sanity-io/ui/pull/1247
> fix: only require `type: commonjs` when `legacyExports: false`

- package.json
- playground/dummy-lodash-es/package.config.ts
- playground/dummy-lodash-es/package.json
- playground/dummy-lodash-es/src/index.ts
- playground/dummy-lodash-es/test.cjs
- playground/dummy-lodash-es/test.mjs
- playground/dummy-lodash-es/tsconfig.dist.json
- playground/dummy-lodash-es/tsconfig.json
- playground/dummy-lodash-es/tsconfig.settings.json
- playground/dummy-lodash/package.config.ts
- playground/dummy-lodash/package.json
- playground/dummy-lodash/src/index.ts
- playground/dummy-lodash/test.cjs
- playground/dummy-lodash/test.mjs
- playground/dummy-lodash/tsconfig.dist.json
- playground/dummy-lodash/tsconfig.json
- playground/dummy-lodash/tsconfig.settings.json
- pnpm-lock.yaml
- src/node/core/config/types.ts
- src/node/tasks/rollup/resolveRollupConfig.ts
It's enabled by default if it detects `lodash` in your `dependencies` or `peerDependencies`.
It can be force disabled by setting:
```ts
import {defineConfig} from '@sanity/pkg-utils'
export default defineConfig({
rollup: {
optimizeLodash: false,
},
})
```
It can also be force enabled:
```ts
import {defineConfig} from '@sanity/pkg-utils'
export default defineConfig({
rollup: {
optimizeLodash: true,
},
})
```
You can change the underlying settings of the `@optimize-lodash/rollup-plugin` plugin by passing an option (this also counts as `optimizeLodash: true`):
```ts
import {defineConfig} from '@sanity/pkg-utils'
export default defineConfig({
rollup: {
optimizeLodash: {
appendDotJs: false, // it's `true` by default
},
},
})
```
If there's `lodash-es` in your `dependencies` or …
> feat: add lodash optimization

- package.json
- pnpm-lock.yaml
- test/verifyTypeScriptVersion.test.ts
> fix: allow wider `typescript` semver range

- package.json
- src/node/tasks/rollup/resolveRollupConfig.ts
When debugging builds it's annoying when export identifiers are minified, even when minify isn't enabled (it requires `minify: true` in the `package.config.ts`):
```
Export "P" of module "node_modules/sanity/lib/_chunks-es/StructureToolProvider.mjs" was reexported through module "node_modules/sanity/lib/structure.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
```
`P`? What's `P`? Now I have to open the build file to figure out what that is. This PR turns off the underlying rollup feature that is causing export identifiers to be minified in internal code 😌
> fix: only enable `minifyInternalExports` by default when `minify: true`

- package.json
- playground/babel-plugin/package.config.ts
- playground/babel-plugin/package.json
- playground/use-client-directive/package.config.ts
- playground/use-client-directive/package.json
- playground/use-client-directive/src/_exports.tsx
- pnpm-lock.yaml
- src/node/core/config/types.ts
- src/node/core/pkg/validatePkg.ts
- src/node/resolveBuildContext.ts
- src/node/resolveBuildTasks.ts
- src/node/tasks/dts/getTargetPaths.ts
- src/node/tasks/index.ts
- src/node/tasks/rollup/index.ts
- src/node/tasks/rollup/resolveRollupConfig.ts
- src/node/tasks/rollup/rollupReactCompilerTask.ts
- src/node/tasks/types.ts
Allows shipping React Compiler output as a separate conditional export condition:
```json
{
"type": "module",
"exports": {
".": {
"source": "./src/index.ts",
"react-compiler": {
"source": "./src/index.ts",
"default": "./dist/index.react-compiler.js"
},
"require": "./dist/index.cjs",
"default": "./dist/index.js"
}
}
}
```
There are a few intentional limits:
- The `react-compiler` condition only supports ESM output, no CJS.
- The compile target for `react-compiler` sets browser targets, not node, as compiled code is supposed to run in the browser (during SSR, or react server component rendering, there is no lifecycles and thus no need to memoize).
- You have to specify a `source` condition in the `react-compiler` condition, even if it's the same as the parent `source`. I left todos in the …
> feat: add `rollup:react-compiler` task

- package.json
- playground/use-client-directive/package.config.ts
- src/node/core/config/types.ts
- src/node/core/contexts/buildContext.ts
- src/node/resolveBuildContext.ts
- src/node/tasks/dts/doExtract.ts
Fixes #967
Can be tested with `pnpm add @sanity/pkg-utils@canary --save-dev`
> fix: add non-external deps to `bundledPacages` by default

- package.json
- scripts/watch.ts
- src/node/tasks/dts/dtsWatchTask.ts
Removes the need for `turbo watch dev` patterns as we've been using in https://github.com/sanity-io/visual-editing, as `pkg watch` now rebuilds .dts files on changes 🥳 
Can be tested with `pnpm i @sanity/pkg-utils@canary`
> feat(watcher): add support for dts incremental rebuilds

- package.json
- src/node/core/config/loadConfig.ts
- src/node/core/pkg/loadPkgWithReporting.ts
- src/node/core/pkg/parseExports.ts
- src/node/core/pkg/types.ts
- src/node/index.ts
- src/node/logger.ts
- src/node/strict.ts
- src/node/tasks/dts/getExtractMessagesConfig.ts
Exports marked with `@internal` are no longer exported, this makes the resulting bundle leaner, and makes it clearer what's part of the public API, and what's not.
> fix: remove internal exports

- package.config.ts
- playground/sanity/package.config.ts
- playground/ts-rolldown-without-extract/tsconfig.dist.json
- playground/ts-rolldown/tsconfig.dist.json
- src/node/check.ts
It's now possible to disable `@microsoft/api-extractor` checks by using:
```ts
import {defineConfig} from '@sanity/pkg-utils'
export default defineConfig({
extract: {
enabled: false
}
})
```
By default `@microsoft/api-extractor` is still used to bundle `.d.ts` files in this mode.
You can completely disable it by also opting into using `rolldown` for `.d.ts` generation:
```ts
import {defineConfig} from '@sanity/pkg-utils'
export default defineConfig({
extract: {
enabled: false
},
dts: 'rolldown'
})
```
> feat: option for disabling API extractor checks

- playground/ts/package.json
- src/cli/buildAction.ts
- src/cli/index.ts
- src/node/build.ts
- src/node/logger.ts
- src/node/spinner.ts
- test/__snapshots__/cli.test.ts.snap
- test/cli.test.ts
- Add --quiet flag to build command that suppresses build progress output
- Preserves errors, warnings, and --check output for debugging
- Useful for automated scripts and AI agents to reduce token usage
- **CLI**: Add --quiet option to build command with proper help text
- **Logger**: Conditionally suppress log, info, and success messages in quiet mode
- **Spinner**: Suppress spinner output in quiet mode while preserving error indicators
- **Build/Check**: Pass quiet flag through the build and check pipeline
- **Tests**: Add test to verify quiet mode functionality
Following standard CLI conventions:
- Suppresses: Build progress messages, info logs, success messages, spinners
- Preserves: Errors, warnings, --check output if passed
- New test verifies build output is suppressed with …
> feat: add --quiet flag to build command

- src/node/tasks/rollup/resolveRollupConfig.ts
Reverts sanity-io/pkg-utils#1548, as it has caused regressions in repos like `@portabletext/editor`
> fix(rollup): revert improve treeshake for react and styled components

- .github/CODEOWNERS
- package.json
- pnpm-lock.yaml
- scripts/build.ts
- scripts/check.ts
- scripts/init.ts
- scripts/watch.ts
- src/global.ts
- src/node/core/config/loadConfig.ts
- src/node/core/config/types.ts
- src/node/index.ts
- removes CODEOWNERS as team ecosystem no longer owns the repo.
- renames `globalThis.__DEV__` usage to `globalThis.___DEV___` as `__DEV__` has special meaning both for the `babel-plugin-react-compiler` as well as the sanity monorepo build tooling.
- removes manual typings and uses the `.d.ts` typings that now ship with `babel-plugin-react-compiler`
> feat: use typings from babel-plugin-react-compiler

- .npmrc
- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
Fixes warnings like:
```sh
npm warn Unknown project config "public-hoist-pattern". This will stop working in the next major version of npm.
```
By moving pnpm options out of the `.npmrc` and into `pnpm-workspace.yaml`.
Since the overall shift is to use `pnpm-workspace.yaml` to generally configure pnpm I've also moved options from `package.json#pnpm` there.
> refactor: move `.npmrc` and `package.json` settings to `pnpm-workspace.yaml`
